AllCops:
  Exclude:
    - 'Guardfile'
    - "db/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "bin/**/*"
    - "log/**/*"

# AlignParameters:
#   Enabled: false

Style/Encoding:
  Enabled: false

# ClassLength:
#   Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

# HashSyntax:
#  EnforcedStyle: hash_rockets

Style/Documentation:
  Enabled: false

# PerceivedComplexity:
#   Enabled: false

# CyclomaticComplexity:
#   Enabled: false

Naming/FileName:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false